<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>git_graph</RootNamespace>
    <AssemblyName>GitGraphApp</AssemblyName>
    <PublishSingleFile>true</PublishSingleFile>
    <PublishAot>true</PublishAot>
    <GenerateEmbeddedFilesManifest>true</GenerateEmbeddedFilesManifest>
  </PropertyGroup>
  <ItemGroup>
    <EmbeddedResource Include="media\**" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Drk.AspNetCore.MinimalApiKit" Version="0.9.7" />
    <PackageReference Include="Microsoft.Extensions.FileProviders.Embedded" Version="10.0.5" />
  </ItemGroup>
</Project>
