using System.Text.Json;
using System.Text.Json.Serialization;
using git_graph.Models;

namespace git_graph.Models.Serialization;

[JsonSourceGenerationOptions(
    PropertyNamingPolicy = JsonKnownNamingPolicy.CamelCase,
    PropertyNameCaseInsensitive = true,
    DefaultIgnoreCondition = JsonIgnoreCondition.Never)]
// JsonElement is the hub method parameter type; SignalR's JSON protocol must be able
// to deserialize it using only this context (no reflection fallback in AOT mode).
[JsonSerializable(typeof(JsonElement))]
[JsonSerializable(typeof(RequestMessage))]
[JsonSerializable(typeof(RequestLoadCommits))]
[JsonSerializable(typeof(RequestLoadRepoInfo))]
[JsonSerializable(typeof(RequestLoadRepos))]
[JsonSerializable(typeof(RequestLoadConfig))]
[JsonSerializable(typeof(RequestCommitDetails))]
[JsonSerializable(typeof(RequestCompareCommits))]
[JsonSerializable(typeof(RequestTagDetails))]
[JsonSerializable(typeof(RequestViewDiff))]
[JsonSerializable(typeof(RequestViewDiffWithWorkingFile))]
[JsonSerializable(typeof(RequestViewFileAtRevision))]
[JsonSerializable(typeof(RequestOpenFile))]
[JsonSerializable(typeof(RequestAddRemote))]
[JsonSerializable(typeof(RequestDeleteRemote))]
[JsonSerializable(typeof(RequestEditRemote))]
[JsonSerializable(typeof(RequestPruneRemote))]
[JsonSerializable(typeof(RequestFetch))]
[JsonSerializable(typeof(RequestDeleteRemoteBranch))]
[JsonSerializable(typeof(RequestFetchIntoLocalBranch))]
[JsonSerializable(typeof(RequestAddTag))]
[JsonSerializable(typeof(RequestDeleteTag))]
[JsonSerializable(typeof(RequestPushTag))]
[JsonSerializable(typeof(RequestCheckoutBranch))]
[JsonSerializable(typeof(RequestCheckoutCommit))]
[JsonSerializable(typeof(RequestCreateBranch))]
[JsonSerializable(typeof(RequestDeleteBranch))]
[JsonSerializable(typeof(RequestRenameBranch))]
[JsonSerializable(typeof(RequestPullBranch))]
[JsonSerializable(typeof(RequestPushBranch))]
[JsonSerializable(typeof(RequestCreatePullRequest))]
[JsonSerializable(typeof(RequestCherrypickCommit))]
[JsonSerializable(typeof(RequestDropCommit))]
[JsonSerializable(typeof(RequestResetToCommit))]
[JsonSerializable(typeof(RequestRevertCommit))]
[JsonSerializable(typeof(RequestCleanUntrackedFiles))]
[JsonSerializable(typeof(RequestResetFileToRevision))]
[JsonSerializable(typeof(RequestMerge))]
[JsonSerializable(typeof(RequestRebase))]
[JsonSerializable(typeof(RequestApplyStash))]
[JsonSerializable(typeof(RequestBranchFromStash))]
[JsonSerializable(typeof(RequestDropStash))]
[JsonSerializable(typeof(RequestPopStash))]
[JsonSerializable(typeof(RequestPushStash))]
[JsonSerializable(typeof(RequestOpenExternalDirDiff))]
[JsonSerializable(typeof(RequestCreateArchive))]
[JsonSerializable(typeof(RequestEditUserDetails))]
[JsonSerializable(typeof(RequestDeleteUserDetails))]
[JsonSerializable(typeof(RequestStartCodeReview))]
[JsonSerializable(typeof(RequestUpdateCodeReview))]
[JsonSerializable(typeof(RequestEndCodeReview))]
[JsonSerializable(typeof(RequestSetGlobalViewState))]
[JsonSerializable(typeof(RequestSetWorkspaceViewState))]
[JsonSerializable(typeof(RequestSetRepoState))]
[JsonSerializable(typeof(RequestNoOp))]
[JsonSerializable(typeof(RefreshResponse))]
[JsonSerializable(typeof(ErrorResponse))]
[JsonSerializable(typeof(RepoErrorResponse))]
[JsonSerializable(typeof(MultiErrorResponse))]
[JsonSerializable(typeof(ViewUrlResponse))]
[JsonSerializable(typeof(OpenFileResponse))]
[JsonSerializable(typeof(LoadCommitsResponse))]
[JsonSerializable(typeof(LoadRepoInfoResponse))]
[JsonSerializable(typeof(LoadReposResponse))]
[JsonSerializable(typeof(LoadConfigResponse))]
[JsonSerializable(typeof(CommitDetailsResponse))]
[JsonSerializable(typeof(CompareCommitsResponse))]
[JsonSerializable(typeof(TagDetailsResponse))]
[JsonSerializable(typeof(AddTagResponse))]
[JsonSerializable(typeof(PushTagResponse))]
[JsonSerializable(typeof(CheckoutBranchResponse))]
[JsonSerializable(typeof(DeleteBranchResponse))]
[JsonSerializable(typeof(PushBranchResponse))]
[JsonSerializable(typeof(CreatePullRequestResponse))]
[JsonSerializable(typeof(MergeResponse))]
[JsonSerializable(typeof(RebaseResponse))]
[JsonSerializable(typeof(StartCodeReviewResponse))]
[JsonSerializable(typeof(CodeReviewIdResponse))]
[JsonSerializable(typeof(EndCodeReviewResponse))]
[JsonSerializable(typeof(SetRepoStateResponse))]
[JsonSerializable(typeof(InitialStateResponse))]
[JsonSerializable(typeof(GitGraphViewInitialState))]
[JsonSerializable(typeof(GitGraphViewConfig))]
[JsonSerializable(typeof(GitGraphViewGlobalState))]
[JsonSerializable(typeof(GitGraphViewWorkspaceState))]
[JsonSerializable(typeof(LoadGitGraphViewTo))]
[JsonSerializable(typeof(LoadGitGraphViewToCommitDetails))]
[JsonSerializable(typeof(Dictionary<string, GitRepoState>))]
[JsonSerializable(typeof(Dictionary<string, GitRepoConfigBranch>))]
[JsonSerializable(typeof(GitRepoState))]
[JsonSerializable(typeof(IssueLinkingConfig))]
[JsonSerializable(typeof(PullRequestConfig))]
[JsonSerializable(typeof(PullRequestCustomConfig))]
[JsonSerializable(typeof(CheckoutBranchPullAfterwards))]
[JsonSerializable(typeof(CodeReview))]
[JsonSerializable(typeof(GitCommit[]))]
[JsonSerializable(typeof(GitCommit))]
[JsonSerializable(typeof(GitCommitTag[]))]
[JsonSerializable(typeof(GitCommitTag))]
[JsonSerializable(typeof(GitCommitRemote[]))]
[JsonSerializable(typeof(GitCommitRemote))]
[JsonSerializable(typeof(GitCommitStash))]
[JsonSerializable(typeof(GitCommitDetails))]
[JsonSerializable(typeof(GitSignature))]
[JsonSerializable(typeof(GitFileChange[]))]
[JsonSerializable(typeof(GitFileChange))]
[JsonSerializable(typeof(GitStash[]))]
[JsonSerializable(typeof(GitStash))]
[JsonSerializable(typeof(GitTagDetails))]
[JsonSerializable(typeof(GitRepoConfig))]
[JsonSerializable(typeof(GitRepoSettingsRemote[]))]
[JsonSerializable(typeof(GitRepoSettingsRemote))]
[JsonSerializable(typeof(GitRepoConfigUser))]
[JsonSerializable(typeof(GitRepoConfigUserLocal))]
[JsonSerializable(typeof(string[]))]
[JsonSerializable(typeof(int[]))]
public partial class GitGraphPayloadJsonContext : JsonSerializerContext
{
}